[project]
name = 'faculty_of_health_sciences'

[unit]
research_unit = 'Research Unit X'

[years]
minimum = 2021
maximum = 2023
reference = 2023

[look]
palette = 'YlGnBu'

[search]
limit = 1000
skip = 0